#!/usr/bin/env bash

apt update &> output_ignored
apt install ecj java-wrappers -y &> output_ignored

cp /autograder/source/results_template /autograder/results/results.json

for file in /autograder/submission/*
do
file=${file##*./}
pkg=$(head -1 $file | cut -d " " -f 2 | cut -d ";" -f 1)
if [ "$OUT" != *"Test"* ]
then
mkdir /autograder/source/src/$pkg &> output_ignored
cp -n $file /autograder/source/src/$pkg
fi
done

cd /autograder/source
mkdir bin

dos2unix ./run.sh &> output_ignored
bash ./run.sh
