#!/usr/bin/env bash

# This is what Gradescope runs first. Start by updating the system and installing ECJ
apt update &> output_ignored
apt install ecj java-wrappers -y &> output_ignored

# Copy the general failure results file just in case
cp /autograder/source/results_template /autograder/results/results.json

# Copy student code to source directory. Ignores all files with "Test" in the name
for file in /autograder/submission/*
do
file=${file##*./}
pkg=$(head -1 $file | cut -d " " -f 2 | cut -d ";" -f 1)
if [ "$OUT" != *"Test"* ]
then
mkdir /autograder/source/src/$pkg &> output_ignored
cp -n $file /autograder/source/src/$pkg
fi
done

# Prep for compilation
cd /autograder/source
mkdir bin

dos2unix ./run.sh &> output_ignored
bash ./run.sh
