#!/usr/bin/env bash

cp /autograder/source/results_template /autograder/results/results.json

for file in /autograder/submission/*
do
file=${file##*./}
pkg=$(head -1 $file | cut -d " " -f 2 | cut -d ";" -f 1)
mkdir /autograder/source/src/$pkg &> output_ignored
cp -n $file /autograder/source/src/$pkg
done

cd /autograder/source
mkdir bin

dos2unix ./run.sh &> output_ignored
bash ./run.sh
