#!/usr/bin/env bash

DOWNLOAD_LINK=$(jq -r '.additional_options.starter_code_download' /autograder/source/config.json)

# If this is the first submission, provide the download link
prev=$(jq '.previous_submissions' submission_metadata.json)
if [ "$prev" == "[]" ]
then
    cd /autograder/source
    output=$(jq -r '.tests[0].output' download_starter_code_template)
    jq --arg data "$output [$DOWNLOAD_LINK]($DOWNLOAD_LINK)" '.tests[0].output = $data' download_starter_code_template > /autograder/results/results.json
    exit 1
fi

# Continue if this isn't the first submission
# Copy the general failure results file just in case
output=$(jq -r '.tests[0].output' /autograder/source/results_error_template)
jq --arg data "$output [$DOWNLOAD_LINK]($DOWNLOAD_LINK)" '.tests[0].output = $data' /autograder/source/results_error_template > /autograder/results/results.json

# Copy student code to source directory. Ignores all files with "Test" in the name
for file in /autograder/submission/*
do
    file=${file##*./}
    pkg=$(head -1 $file | cut -d " " -f 2 | cut -d ";" -f 1)
    pkg=$(echo "$pkg" | sed 's/\./\//g')
    if [[ "$pkg" != *"Test"* ]] && [[ "$file" != *"RunAllTests"* ]]
    then
        mkdir /autograder/source/src/$pkg &> /dev/null
        cp -n $file /autograder/source/src/$pkg &> /dev/null
    fi
done

# Prep for compilation
cd /autograder/source
mkdir bin &> /dev/null

dos2unix ./run.sh &> /dev/null
bash ./run.sh
