#!/usr/bin/env bash

DOWNLOAD_LINK="https://link.canon.click/autograder/startercode" # Provide the link for students to download starter code

# This is what Gradescope runs first. Start by updating system packages and installing jq
apt update &> /dev/null
apt install jq -y &> /dev/null

# If this is the first submission, provide the download link
prev=$(jq '.previous_submissions' submission_metadata.json)
if [ "$prev" == "[]" ]
then
    cd /autograder/source
    output=$(jq -r '.tests[0].output' download_starter_code_template)
    jq --arg data "$output [$DOWNLOAD_LINK]($DOWNLOAD_LINK)" '.tests[0].output = $data' download_starter_code_template > /autograder/results/results.json
    exit 1
fi

# Continue if this isn't the first submission
apt install ecj java-wrappers -y &> /dev/null

# Copy the general failure results file just in case
cp /autograder/source/results_error_template /autograder/results/results.json

# Copy student code to source directory. Ignores all files with "Test" in the name
for file in /autograder/submission/*
do
    file=${file##*./}
    pkg=$(head -1 $file | cut -d " " -f 2 | cut -d ";" -f 1)
    pkg=$(echo "$pkg" | sed 's/\./\//g')
    if [[ "$pkg" != *"Test"* ]] && [[ "$file" != *"RunAllTests"* ]]
    then
        mkdir /autograder/source/src/$pkg &> /dev/null
        cp -n $file /autograder/source/src/$pkg
    fi
done

# Prep for compilation
cd /autograder/source
mkdir bin &> /dev/null

dos2unix ./run.sh &> /dev/null
bash ./run.sh
