#!/usr/bin/env bash

# Check if any Java files were submitted
file_count=$(find submission -type f -iname "*.java" | wc -l)
if [ $file_count -eq 0 ]; then
    cp /autograder/source/results_template_no_java_files /autograder/results/results.json
    exit 1
fi

# Check if file names match config
missing_files=()
while read -r required_file; do
    matches=$(find submission -type f -iname "$required_file")
    if [ -z $matches ]; then
        missing_files+=("$required_file")
    else
        # Remove file from directory if found
        mkdir -p tmp
        mv $matches tmp/
    fi
done < <(jq -r '.["required-files"][]' /autograder/source/config.json | sort -r)

# Restore submission directory
mv tmp/* submission/
rmdir tmp

if [ ${#missing_files[@]} -gt 0 ]; then
    cp /autograder/source/results_template_missing_files /autograder/results/results.json
    missing_files_out=""
    for missing_file in "${missing_files[@]}"; do
        missing_files_out+="- $missing_file\\\\n"
    done
    sed -i "s/\[list\]/$missing_files_out/g" /autograder/results/results.json
    exit 1
fi

# Print success message
cp /autograder/source/results_template_success /autograder/results/results.json
