name: Update template version

on:
  pull_request:
    paths:
      - "templates/autograded/**"
      - "templates/manual/**"

jobs:
  update-autograded-template:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Check if autograded files were changed
        run: |
          if git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep -q '^templates/autograded/'; then
            echo "autograded_changed=true" >> $GITHUB_ENV
          else
            echo "autograded_changed=false" >> $GITHUB_ENV
          fi
      - name: Update autograded template version
        if: env.autograded_changed == 'true'
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$(date +"%Y.%m.%d-%H%M")\"/" templates/autograded/version.json
      - name: Check if manual files were changed
        run: |
          if git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep -q '^templates/manual/'; then
            echo "manual_changed=true" >> $GITHUB_ENV
          else
            echo "manual_changed=false" >> $GITHUB_ENV
          fi
      - name: Update manual template version
        if: env.manual_changed == 'true'
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"$(date +"%Y.%m.%d-%H%M")\"/" templates/manual/version.json
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update template versions"
          git push origin $HEAD_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}