name: Update template version

on:
  pull_request:
    paths:
      - "templates/autograded/**"
      - "templates/manual/**"

jobs:
  update-template-versions:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Update template versions
        run: |
          VERSION=$(date +"%Y.%m.%d-%H%M")
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" templates/autograded/version.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" templates/manual/version.json
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[ci skip] Update template versions"
          git push origin $HEAD_REF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
